# Generated by Django 3.0.6 on 2020-05-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import noticeboard.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('BME', 'BME'), ('PME', 'PME'), ('TE', 'TE'), ('ChE', 'ChE'), ('EST', 'EST'), ('NFT', 'NFT'), ('APPT', 'APPT'), ('CDM', 'CDM'), ('FMB', 'FMB'), ('GEBT', 'GEBT'), ('Pharmacy', 'Pharmacy'), ('MB', 'MB'), ('PESS', 'PESS'), ('NHS', 'NHS'), ('English', 'English'), ('AIS', 'AIS'), ('Management', 'Management'), ('F&B', 'F&B'), ('Marketing', 'Marketing')], max_length=100)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='book/pdfs/', validators=[noticeboard.validators.validate_file_extension])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
    ]
